apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  rules:
  - http:
      paths:
      - pathType: "Prefix"
        path: "/"
        backend:
          service:
            name: {{ .Release.Name | quote }}
            port: 
              number: {{ .Values.servicePort }}
