apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}